baseURL = "https://richard-fagot.github.io/"
DefaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "Richard Fagot"
theme = "beautifulhugo"
googleAnalytics = "UA-165981365-1"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Apprendre, Tester, Bricoler, Transmettre"
  logo = "img/avatar.png" # Expecting square dimensions
  favicon = "img/favicon.png"
  dateFormat = "2 January 2006"
  mainSections = ["post","posts"]

  [Author]
  name = "Richard Fagot"
  website = "https://richard-fagot.github.io/"
  github = "richard-fagot"
  linkedin = "richardfagot"
  twitter = "@richardfagot"